config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do
    get 'upvote', on: :member
    get 'downvote', on: :member
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, :location, :upVotes, :downVotes, presence: true
def self.search(search)
  where("Name LIKE ? OR Location LIKE ?", "%#{search}%", "%#{search}%") 
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
	if params[:search]
	  @restaurants = Restaurant.search(params[:search]).order("created_at DESC")
	else
	  @restaurants = Restaurant.all.order("created_at DESC")
	end
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @restaurant = Restaurant.find(params[:id])
    @restaurant.increment!(:upVotes)
    redirect_to restaurants_url
  end

  def downvote
    @restaurant = Restaurant.find(params[:id])
    @restaurant.increment!(:downVotes)
    redirect_to restaurants_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :location, :upVotes, :downVotes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Splitthecheck</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for(restaurant) do |f| %>
  <% if restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>

  <div class="field">
    <%= f.label :upVotes %>
    <%= f.number_field :upVotes %>
  </div>

  <div class="field">
    <%= f.label :downVotes %>
    <%= f.number_field :downVotes %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Restaurants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Up-votes</th>
      <th>Down-votes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

	

<%= form_tag(restaurants_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search Restaurants" %>
 <%= submit_tag "Search", :name => nil %>
<% end %>

<% if @restaurants.blank? %>
<h2>Could not find anything that matched your search</h2>
<%  @restaurants = Restaurant.all %>
<% end %>


  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.location %></td>
        <td><%= restaurant.upVotes %></td>
        <td><%= restaurant.downVotes %></td>
        <td><%= link_to 'Show', restaurant %></td>
        <td><%= link_to 'vote up', upvote_restaurant_path(restaurant) %></td>
        <td><%= link_to 'vote down', downvote_restaurant_path(restaurant) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @restaurant.location %>
</p>

<p>
  <strong>Up-votes:</strong>
  <%= @restaurant.upVotes %>
</p>

<p>
  <strong>Down-votes:</strong>
  <%= @restaurant.downVotes %>
</p>

<%= link_to 'Back', restaurants_path %>